name = "fmovies4u-sitemap"
compatibility_date = "2024-05-18"
pages_build_output_dir = "./dist" # or your Vite build output folder

[build]
command = "npm run build"

[[functions]]
directory = "functions"
